# -*- coding: utf-8 -*-
"""Exerciciomod1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AFErST6Z4HIJ9KSlkoLpjqyh9mt_s1Zs
"""

# inserir nome de usuário
nome_usuario = input ( "Digite seu nome : ")
# inserir Olá usuario
print (f"Ola,{nome_usuario}!")

while True:
  # inserir numeros 1 e 2
  numero1 = int(input ("Digite o primeiro numero:"))
  numero2 = int(input("Digite o segundo número:"))
  # inserir operação
  operacao = input("Digite a operacao (+,-,*,ou /):")
  # realizar calculo escolhido
  if operacao == '+':
   print (f"a soma dos números é = : {numero1+numero2}")
  elif operacao == '-':
   print(f"a subtraçao dos números é = : {numero1-numero2}")
  elif operacao == '*':
   print (f"a multiplicação dos números é = : {numero1*numero2}")
  elif operacao == '/':
   print (f"a divisão dos números é = : {numero1/numero2}")
  else :
   print (f"operação inválida")
  # inserir opção para voltar ao passo "inserir numeros 1 e 2"
  opcao = input("Deseja realizar outra operação? (s/n)")
  if opcao.lower() != 's':
   print(f"Até mais,{nome_usuario}!")
   break